domain: pythonoperatorframework.io

image: prod-comms.ps5.docker-registry.canonical.com/pythonoperatorframework.io

env:
  - name: SENTRY_DSN
    value: https://d7ced21757484655afc98ce089955dab@sentry.is.canonical.com//43

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'pythonoperatorframework.io' ) {
      rewrite ^ https://pythonoperatorframework.io$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect, <https://res.cloudinary.com>; rel=preconnect";

    # Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect, <https://res.cloudinary.com>; rel=preconnect";
